name: wisata_indonesia
description: Aplikasi wisata Indonesia
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.28.0
  firebase_auth: ^4.17.3
  
  # UI & Utilities
  cached_network_image: ^3.3.0
  provider: ^6.1.1
  intl: ^0.19.0
  shared_preferences: ^2.2.2  # Untuk dark mode
  
  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0   # Untuk generate launcher icon

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/logo.jpg
    - assets/icon/icon.png   # Launcher icon

# Konfigurasi flutter_launcher_icons di level root
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"